import '../css/globals.css'
import { Inter } from 'next/font/google'
import Banner from './layout/banner'
import Info from './layout/info'
import Menu from './layout/menu'
import Footer from './layout/footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app'
// }

export default function RootLayout({ children }) {
	return (
		<html lang="ru">
			<body className={inter.className}>
				<Banner />
				<Info />
				<Menu />
				{children}
				<Footer />
			</body>
		</html>
	)
}
